## docker run --name=DB -e POSTGRES_USER=^a database user^ -e POSTGRES_PASSWORD=^a database password^ -e POSTGRES_DB=^a database name^ -d postgres
## docker run -d -P --name moodle --link DB:DB -e MOODLE_DB_HOST=DB -e MOODLE_URL=http://63.250.53.14:8080 -e MOODLE_DB_TYPE="pgsql" -p 8080:80 ellakcy/moodle:postgresql_apache_^VERSION^
## https://kubernetes.io/docs/reference/kubectl/docker-cli-to-kubectl/
## docker run -d --restart=always -e DOMAIN=cluster --name nginx-app -p 80:80 nginx
##  kubectl create deployment --image=nginx nginx-app
## expose a port through with a service
## kubectl expose deployment nginx-app --port=80 --name=nginx-http
## $ kubectl run NAME --image=image [--env="key=value"] [--port=port] [--dry-run=server|client] [--overrides=inline-json] [--command] -- [COMMAND] [args...]

## Example approach
## 1. Create a base Pod Manifest using the kubectl run command with appropriate flags.

# kubectl create namespace dev-env

# kubectl get namespace

# kubectl run saamlmsdb-pod --env=["POSTGRES_USER=slpgrusename","POSTGRES_PASSWORD=SaamS0ft123","POSTGRES_DB=slpgrdb"] -d postgres

# kubectl run saamlms-pod --image=ellakcy/moodle:postgresql_apache_403_php8.1 --env=["MOODLE_DB_HOST=DB","MOODLE_DB_TYPE="pgsql"]  --namespace dev-env --port=80 --expose=true --attach=true --dry-run=client -o yaml > saamlms-pod.yaml

version: '2'

services:

  nginx:
   image: nginx:alpine
   ports:
     - '8082:8082'
   volumes:
     - './conf/nginx.conf:/etc/nginx/nginx.conf:ro'
     - './logs/:/var/log/nginx'
     - 'www_psql_alpine_fpm:/var/www/html'
   links:
     - 'moodle'
   volumes_from:
     - 'moodle'

  moodle_db:
    image: postgres:11
    volumes:
      - 'moodledb_psql_alpine_fpm :/var/lib/postgresql/data'
      - './data/moodle/www:/var/www/html'
    environment:
      POSTGRES_DB: '${MOODLE_DB_NAME}'
      POSTGRES_USER: '${MOODLE_DB_USER}'
      POSTGRES_PASSWORD: '${MOODLE_DB_PASSWORD}'

  moodle:
    image: ellakcy/moodle:postgresql_fpm_alpine_latest
    volumes:
      - './data/moodle:/var/moodledata'
      - 'www_psql_alpine_fpm:/var/www/html'
    links:
      - 'moodle_db'
    environment:
      MOODLE_URL: $MOODLE_URL
      MOODLE_ADMIN: $MOODLE_ADMIN
      MOODLE_ADMIN_PASSWORD: $MOODLE_ADMIN_PASSWORD
      MOODLE_ADMIN_EMAIL: $MOODLE_ADMIN_EMAIL
      MOODLE_DB_HOST: 'moodle_db'
      MOODLE_DB_USER: $MOODLE_DB_USER
      MOODLE_DB_PASSWORD: $MOODLE_DB_PASSWORD
      MOODLE_DB_NAME: $MOODLE_DB_NAME
      MOODLE_REVERSE_LB: $MOODLE_REVERSE_LB
      MOODLE_SSL: $MOODLE_SSL
      MOODLE_EMAIL_TYPE_QMAIL: $MOODLE_EMAIL_TYPE_QMAIL
      MOODLE_EMAIL_HOST: $MOODLE_EMAIL_HOST

volumes:
  moodledb_psql_alpine_fpm :
  www_psql_alpine_fpm:
